volumes:
  production_postgres_ninja_hosts_data: {}
  production_postgres_ninja_hosts_data_backups: {}
  production_ninja_hosts_media: {}
  production_ninja_hosts_static: {}
  production_redis_ninja_hosts_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: ninja_hosts_production_ninja_hosts
    volumes:
      - production_ninja_hosts_media:/app/ninja_hosts/media
      - production_ninja_hosts_static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start
    ports:
      - "9010:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfilje
    image: ninja_hosts_production_postgres
    volumes:
      - production_postgres_ninja_hosts_data:/var/lib/postgresql/data
      - production_postgres_ninja_hosts_data_backups:/backups
    env_file:
      - .env


  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_ninja_hosts_data:/data


  celeryworker:
    <<: *django
    image: ninja_hosts_production_celeryworker
    command: /start-celeryworker
    ports: [ ]

  celerybeat:
    <<: *django
    image: ninja_hosts_production_celerybeat
    command: /start-celerybeat
    ports: [ ]

  flower:
    <<: *django
    image: ninja_hosts_production_flower
    command: /start-flower
    ports:
      - "9055:5555"

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: ninja_hosts_production_nginx
    depends_on:
      - django
    volumes:
      - production_ninja_hosts_media:/usr/share/nginx/media:ro
      - production_ninja_hosts_static:/usr/share/nginx/static:ro
    ports:
      - "9011:80"
 