volumes:
  ninja_demo_local_postgres_data: {}
  ninja_demo_local_postgres_data_backups: {}
  ninja_demo_local_redis_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ninja_demo_local_django
    container_name: ninja_demo_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_HOST=postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ninja_demo_production_postgres
    container_name: ninja_demo_local_postgres
    volumes:
      - ninja_demo_local_postgres_data:/var/lib/postgresql/data
      - ninja_demo_local_postgres_data_backups:/backups
    env_file:
      - .env
    ports:
      - 5432:5432


  redis:
    image: docker.io/redis:6
    container_name: ninja_demo_local_redis
    volumes:
      - ninja_demo_local_redis_data:/data


  celeryworker:
    <<: *django
    image: ninja_demo_local_celeryworker
    container_name: ninja_demo_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ninja_demo_local_celerybeat
    container_name: ninja_demo_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: ninja_demo_local_flower
    container_name: ninja_demo_local_flower
    ports:
      - '5555:5555'
    command: /start-flower